### PR TITLE
toggle bulb

### PR DESCRIPTION
**Pull request by imthevk**
added project toggle bulb with javascript

### CODE REVIEW

**Comment by sajjadrahman56** [comment]
Thank you @Iamthevk . Happy Hactoberfest22

**Comment by sajjadrahman56** [comment]
Hope you will also make a PR about the youtube tech link

**Comment by imthevk** [comment]
@sajjad-njr  youtube tech link what is it?

**Comment by sajjadrahman56** [comment]
@Iamthevk  such as the freecode camp youtube channel.

**Comment by sajjadrahman56** [comment]
**or give me any suggest what should I add ?**

**Pull request merged**
